Audition page done
TritonSE/dynamics-website pull request #48
Opened 2020-05-07 03:13 UTC by ubhattac

2020-05-12 00:35 UTC, jayrc7 requested changes
The page looks really good! For the mobile design of it, the font size of the audition page should be a lot smaller, and I'm thinking it should also be at the top of the screen. Also, just show the second picture for the mobile version, no need to show both. Great job. 

![image](https://user-images.githubusercontent.com/30588403/81625469-e6430a80-93ad-11ea-9c95-63ea9cf3c55d.png)

2020-05-12 01:00 UTC, jayrc7 requested changes

2020-05-12 01:00 UTC, jayrc7 commented on src/components/AuditionEligibility.js
> +                        one hour of ballet, and one hour of another genre of dance.em</li>
Is there supposed to be .em at the end?

2020-05-18 09:28 UTC, jayrc7 requested changes
This looks really good! There's been a tiny change to that page, Danielle wants the pictures to switch places. After making that change the pr is good to go.

2020-05-18 18:28 UTC, ubhattac commented
> This looks really good! There's been a tiny change to that page, Danielle wants the pictures to switch places. After making that change the pr is good to go.


### Switched the pictures
> see below
<img width="1680" alt="Screen Shot 2020-05-18 at 11 27 08 AM" src="https://user-images.githubusercontent.com/37908451/82247047-9b1f7f00-98fa-11ea-9b4e-148ea1ecb6cb.png">

2020-05-18 21:10 UTC, jayrc7 approved these changes
nice

2020-05-18 23:33 UTC, Anshul-Birla approved these changes
Looks good bruv

2020-05-18 23:34 UTC, merged