Finished audition page mobile design
TritonSE/dynamics-website pull request #87
Opened 2020-06-19 08:49 UTC by ubhattac

2020-06-20 10:35 UTC, jayrc7 requested changes
This could be an issue that only shows up on my end but for some reason when trying to view the audition page using an ipad screen, the page won't show up at all.

2020-06-22 23:31 UTC, jayrc7 requested changes
Confirmed today in our meeting, the website shows a blank screen when viewing the audition page with an ipad. It's pretty much a css issue.

2020-06-25 05:13 UTC, TheHiddenLayer reviewed
There's like 76 files changed. Disregard everything except for Audition.css and Audition.js. All the changes are because I recently got an auto-formatter (and it just scanned the entire repo and perfected the style). I forgot to turn off the formatter when working on our TSE repos, but on the bright side we have perfect style now!

2020-06-25 05:15 UTC, ubhattac commented on src/css/Audition.css
> +  }
In conclusion, just direct your attention here. This is most of the important stuff I ended up changing.

2020-06-27 05:29 UTC, jayrc7 approved these changes
Looks great, Thanks Upo!

2020-06-27 05:30 UTC, merged